name: lametric
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pgrimaud/action-lametric@master
        env:
          LAMETRIC_ACCESS_TOKEN: ${{ secrets.LAMETRIC_ACCESS_TOKEN }}
          LAMETRIC_PUSH_URL: ${{ secrets.LAMETRIC_PUSH_URL }}
          NOTIFICATION_ICON: ${{ secrets.NOTIFICATION_ICON }}
          NOTIFICATION_TEXT: ${{ secrets.NOTIFICATION_TEXT }}
